### ISSUE TITLE
Does svg-tag-tags need fixing?

### ISSUE THREAD

**Issue by rvf0068** [rougier/notebook-mode#2]
I have tried this, and the only tags that actually appear are the ones denoting the language in source blocks. Does svg-tag-tags need something similar to what you did in this commit https://github.com/rougier/svg-tag-mode/commit/fee61c6a0b0570bd24fd335efef17c7385297aa0?

**Comment by rougier** [comment]
Oh yes, you're right, thanks. I forgot to update the notebook. I just pushed a fix.

**Comment by rvf0068** [comment]
Thanks, it works now.
