### ISSUE TITLE
Use the (non-gnu|m)elpa repositories for distribution

### ISSUE THREAD

**Issue by amartos** [rougier/notebook-mode#8]
I am not aware of the intricacies of uploading a package to one of the popular repos, thus I'm wondering why this module (and some of your other ones) is not available on those.

Not that it is a very important issue, using git is perfectly fine *per se*.

French translation(ish):

Je ne connais pas les détails pour utiliser les différentes plateformes connues dédiées aux packages emacs, mais je me demandais pourquoi ce module et plusieurs de vos autres modules ne l'étaient pas, étant donné leur popularité.

Ce n'est pas vraiment grave, git suffit en soi, mais c'était une interrogation qui m'a traversé l'esprit.

**Comment by rougier** [comment]
I've upload some package on melpa and from my memory, it was not really straightforward. It could land on ELPA but more tests are probably needed before submitting.

**Comment by amartos** [comment]
I see, that was in my "might-be that" list. 

This might be quite useful for the community in the long term, as the users installing packages through the package list interface may not discover (most of) yours.

But, as I said, installing with `git` is not such a big deal either and is easier with `use-package` and related. And I think most of Emacs users will at some point care enough about the arcane details of their config and go into their `init.el`.

I don't have time for now, but in the future I might look into your packages for help in that regard.
